### ISSUE TITLE
正常运行但会显示php错误

### ISSUE THREAD

**Issue by FFFcat** [SomeBottle/OneIndex#1]
Warning: file_put_contents(/var/www/lib/requestlog.php): failed to open stream: Permission denied in /var/www/lib/onedrive.php on line 126
Warning: file_put_contents(/var/www/lib/requestcode.txt): failed to open stream: Permission denied in /var/www/lib/onedrive.php on line 138
Warning: Cannot modify header information - headers already sent by (output started at /var/www/lib/onedrive.php:126) in /var/www/controller/IndexController.php on line 28
Warning: Cannot modify header information - headers already sent by (output started at /var/www/lib/onedrive.php:126) in /var/www/controller/IndexController.php on line 29
Warning: Cannot modify header information - headers already sent by (output started at /var/www/lib/onedrive.php:126) in /var/www/controller/IndexController.php on line 30

**Comment by SomeBottle** [comment]
前面两个Warning主要问题是php访问目录权限不够，建议设置目录权限为777:  
  chmod -R 777 /var/www/  
后面三个warning是原程序就有的header重复问题，但是并不影响，关闭报错即可。  

Feel free to ask.作为高中生可能周末才有时间回复。
