### ISSUE TITLE
搭建完成后首页提示错误

### ISSUE THREAD

**Issue by oursola** [SomeBottle/OneIndex#2]
Warning: Illegal string offset 'index.html' in /www/wwwroot/sola.fun/controller/IndexController.php on line 113

Warning: Illegal string offset 'index.html' in /www/wwwroot/sola.fun/controller/IndexController.php on line 114

Fatal error: Cannot use string offset as an array in /www/wwwroot/sola.fun/controller/IndexController.php on line 114

**Comment by SomeBottle** [comment]
如果不影响使用可以关闭php报错以屏蔽，这个是原程序范畴的.
