### ISSUE TITLE
无限安装

### ISSUE THREAD

**Issue by Zxilly** [SomeBottle/OneIndex#5]
进不去主页啊

**Comment by SomeBottle** [comment]
请提供详细问题图片和报告再发issue.不然我不知道你在说什么.

**Comment by SomeBottle** [comment]
目前由于学业问题，项目处于保守期，源码可能没有时间修改。如果可以，希望你能提供错误详细情况，我每周只有一天在。

**Comment by Zxilly** [comment]
已解决，顺便github把我发的log吞了。。。
